### ISSUE TITLE
등록, 개인페이지  API 연결

### ISSUE THREAD

**Issue by haemalgeumi** [ChatCode9/ChatCode-frontend#24]
### 📄 Describe

등록페이지와 개인페이지에 있는 avatars 관련 부분 API연결,
admin 관심 태그 관련 API 연결

### ✅ Tasks

- [x] admin interest tag API연결
- [x] avatar API 연결
- [x] avatar interest tag API연결

### 🙋🏻 More

추후에 admin 관련 페이지도 만들면 좋을 것 같습니다!
